### ISSUE TITLE
What is this `Container` design pattern called?

### ISSUE THREAD

**Issue by zwhitchcox** [stevenhauser/i-have-to-return-some-videotapes#11]
I haven't seen this in any other React apps (although, I am admittedly new to the library).

Also, this whole connect and `mapStateToProps` and `mapDispatchToProps` is a little confusing for me.

And this `createPureComponent` thing is a little confusing to me.

I have read all the React and Redux docs though, but still don't really understand what's going on here.

Would you care to point a fellow React traveler in the right direction?

Also, congratulations on creating a unique and interesting game with React.

**Comment by stevenhauser** [comment]
Whoops, I guess I should watch my own repo. I just saw this.

The container components are part of Redux, same with `mapStateToProps` and `mapDispatchToProps`. They're just functions that return objects that get merged into props on the non-container component. `mapStateToProps` is for providing *data* to your component, while `mapDispatchToProps` is for providing *functions* to you component which result in changes to your state/data. The [react-redux docs](https://github.com/rackt/react-redux/blob/master/docs/api.md) do a pretty nice job of explaining this if you haven't checked them out yet.

`createPureComponent` is just a wrapper function to facilitate creating pure rendering components. There are a ton of different ways to do this, this is just one way that I like doing it.

**Comment by stevenhauser** [comment]
Closing since I answered this and there are no further questions, your honor :hammer:
